name: My Test
favicon: null
layout_spectrum: 0.12614
typography_spectrum: 0.59381
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#ffffff'
    - '#378aaa'
    - '#0d5c7d'
    - '#a9dcef'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
