name: My Test
favicon: null
layout_spectrum: 0.715499306563288
typography_spectrum: 0.07295526494272053
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.25633943220600486
  lightness: 0.9822524071205407
  saturation: 0.5204989109188318
  rhythmicContrast: 0.23431014851666987
purpose: []
